"""Add username column to User table

Revision ID: e95a8e63688e
Revises: a566710c57c8
Create Date: 2024-12-31 13:37:09.951102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95a8e63688e'
down_revision = 'a566710c57c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
